version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build, Testing and packing the application..
      - mvn clean package DskipTests
  post_build:
    commands:
      - echo Build, Testing and packing completed.
artifacts:
  files:
    - target/*.jar
cache:
  paths:
    - '/root/.m2/**/*'
