version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Running tests..."
      - mvn test -Dspring.profiles.active=test

reports:
  junit-reports:
    files:
      - target/surefire-reports/*.xml
